# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSBiLSTMCTCModuleWithDropoutSE
  in_features: 528
  mlp_features: [480]
  block_channels: [24, 24, 24, 24]
  kernel_width: 32
  dropout_rate: 0.3
  lstm_hidden: 128
  lstm_layers: 2

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]